export const ENABLE_LOADER = "ENABLE_LOADER";
export const DISABLE_LOADER = "DISABLE_LOADER";

export const FETCH_DASHBOARD = "FETCH_DASHBOARD";
export const SET_DASHBOARD = "SET_DASHBOARD";
export const UPDATE_DASHBOARD = "UPDATE_DASHBOARD";